name: Cypress Cloud

on: 
 workflow_dispatch:
  inputs:
   spec:
    description: Run by cypress command line
    default: cypress/e2e/*

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
     - name: get code
       uses: actions/checkout@v4.2.0

     - name: Cypress run
       uses: cypress-io/github-action@v6.5.0
       with: 
        install-command: yarn install
        browser: electron
        record: true
        group: UI Electron
        spec: ${{ github.event.inputs.spec }}
    env:
       CYPRESS_RECORD_KEY: 2c50b9b6-0f81-4587-9899-273be37a9f49
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
